global:
  scrape_interval: 15s
rule_files:
  - alert.rules.yml
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['localhost:9093']
scrape_configs:
  - job_name: 'test'
    metrics_path: /metrics
    static_configs :
    - targets: 
      - 'localhost:9000'

  - job_name: 'sonarqube'
    metrics_path: /metrics
    static_configs :
    - targets: 
      - 'localhost:9000'
  - job_name: 'sonar'
    metrics_path: /metrics
    static_configs :
    - targets: 
      - 'localhost:9090'

  - job_name: 'ebike'
    metrics_path: /metrics
    static_configs :
    - targets: 
      - '172.18.3.218:9093'

  - job_name: 'ebike2'
    metrics_path: /management/prometheus
    static_configs :
    - targets: 
      - '172.18.3.207:8081'

